### ISSUE TITLE
Json could also be a NSArray

### ISSUE THREAD

**Issue by linlinyao1** [fabiocaccamo/FCFileManager#11]
+(NSDictionary *)readFileAtPathAsJSON:(NSString *)path;

This is assuming JSON file is a dictionary, but it can also be a array

**Comment by fabiocaccamo** [comment]
You're right, the only thing that I don't like is that fixing it the return type must change to NSObject, so in future any value returned by calling this method should be casted to NSArray / NSDictionary.
Have you any idea?

**Comment by linlinyao1** [comment]
To cast return object to NSArray/NSDictionary is the most easy way, and even apple's NSJSONSerialization class is doing this way.

To be compatible with different types, I would suggest Class Clusters, just like NSNumber. But this requires a new JSON wrapper instead of NSArray / NSDictionary, seems too heavy for the need here.

**Comment by fabiocaccamo** [comment]
Just released 1.0.8 pod, thanks.
