### ISSUE TITLE
Enhancement : Read and Write Extended File Attributes

### ISSUE THREAD

**Issue by wm-j-ray** [fabiocaccamo/FCFileManager#13]
Not a pull request, but a mod to allow reading and writing of extended File attributes, cribbed from here: https://github.com/pm-dev/PMUtils/blob/master/Pod/Classes/Foundation%2BPMUtils/NSFileManager%2BPMUtils.m#L62-87

And Mattt Thompson, NSHipster here: http://nshipster.com/extended-file-attributes/

    #import <sys/xattr.h>
    #import <sys/stat.h>

    + (NSString *)xattrStringValueForKey:(NSString *)key atPath:(NSString *)path {
       NSURL *anURL = [FCFileManager urlForItemAtPath:(NSString *)path];
        NSString *value = [self xattrStringValueForKey:(NSString *)key atURL:(NSURL *)anURL];
        return value;
    }

    + (BOOL)setXAttrStringValue:(NSString *)value forKey:(NSString *)key atPath:(NSString *)path {
        NSURL *anURL = [FCFileManager urlForItemAtPath:(NSString *)path];
        BOOL setIt = [self setXAttrStringValue:(NSString *)value forKey:(NSString *)key atURL:(NSURL         *)anURL];
        return setIt;
    }

    + (NSString *)xattrStringValueForKey:(NSString *)key atURL:(NSURL *)URL
    {
        NSString *value = nil;
        const char *keyName = key.UTF8String;
        const char *filePath = URL.fileSystemRepresentation;
    
        ssize_t bufferSize = getxattr(filePath, keyName, NULL, 0, 0, 0);
    
        if (bufferSize != -1) {
            char *buffer = malloc(bufferSize+1);
        
            if (buffer) {
                getxattr(filePath, keyName, buffer, bufferSize, 0, 0);
                buffer[bufferSize] = '\0';
                value = [NSString stringWithUTF8String:buffer];
                free(buffer);
            }
        }
        return value;
    }

    + (BOOL)setXAttrStringValue:(NSString *)value forKey:(NSString *)key atURL:(NSURL *)URL
    {
        int failed = setxattr(URL.fileSystemRepresentation, key.UTF8String, value.UTF8String, value.length, 0, 0);
        return (failed == 0);
    }

**Comment by fabiocaccamo** [comment]
Good idea, I'll implement it as soon as possible. Thanks

**Comment by fabiocaccamo** [comment]
Added full support for read/write xattr and for read images metadata, EXIF data and TIFF data.
Check ```pod 1.0.12```
