### ISSUE TITLE
1.0.12 couldn't compile with Swift

### ISSUE THREAD

**Issue by offfffz** [fabiocaccamo/FCFileManager#15]
I've updated to 1.0.12 with cocoapods and it said missing "#import <sys/xattr.h>".
The project is in swift. The latest version that works is 1.0.10

**Comment by fabiocaccamo** [comment]
The project is an iOS or an OSX project? 
Have you ImageIO.framework under "Build phases / Link binary with libraries" ?
Have you CoreGraphics.framework under "Build phases / Link binary with libraries" ?
