### ISSUE TITLE
Unable to write large file (file size around 900 MB)

### ISSUE THREAD

**Issue by ankitaporwal** [fabiocaccamo/FCFileManager#19]
File manager's [data writeToFile:absolutePath atomically:YES] returns NO for such file sizes, may be a temporary buffer and chunk writing could help. 

<a href="https://dashboard.polar.sh/fabiocaccamo/FCFileManager/issues/19">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/FCFileManager/issues/19/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/FCFileManager/issues/19/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
I will add support for read/write huge files in background with a completion handler.
Which kind of content are you writing? NSData?

**Comment by ankitaporwal** [comment]
Yes.

-- 
Ankita Porwal
Mobility | metacube Softwares Pvt Ltd.
Cell: +91-98285-92488
Skype: ankitaporwal.icloud
Gtalk: ankita.porwal@metacube.com

**Comment by mythodeia** [comment]
any updates on this?

**Comment by fabiocaccamo** [comment]
Unfortunately I had not the time to work seriously on this great feature. In any case feel free to submit a PR.
