### ISSUE TITLE
Wrong nil check for  (NSError **) error

### ISSUE THREAD

**Issue by googoodalls** [fabiocaccamo/FCFileManager#20]
in .m file line 187:

return (error == nil);  should be return ((*error) == nil);

+(BOOL)createFileAtPath:(NSString *)path withContent:(NSObject *)content error:(NSError **)error
{
    if(![self existsItemAtPath:path] && [self createDirectoriesForFileAtPath:path error:error])
    {
        [[NSFileManager defaultManager] createFileAtPath:[self absolutePath:path] contents:nil attributes:nil];
        
        if(content != nil)
        {
            [self writeFileAtPath:path content:content error:error];
        }
        
        return ((*error) == nil);
    }
    
    return NO;
}

**Comment by fabiocaccamo** [comment]
Comparison of address of 'error' equal to a null pointer is always false...

**Comment by googoodalls** [comment]
Hello Sir,

The erorr is (NSError **) ,  not (NSError *) in the line 187 of FCFileManager.m file.
would you please set a break point to the line 187, and use PO command to see the result (error == nil) and ((*error) == nil)?

I try to save a file to document directory successful case.
My test result are:

(lldb) po error
domain: nil - code: 140609485627856

(lldb) po error == nil
<nil>

(lldb) po (*error)
 nil

(lldb) po ((*error) == nil)
true

see screenshot for more details.

<img width="1049" alt="2015-09-28 23 18 23" src="https://cloud.githubusercontent.com/assets/4641653/10139817/50446450-6637-11e5-8f04-65ea6d446069.png">

**Comment by fabiocaccamo** [comment]
You're right, the actual check returns always NO and it need to be fixed, but your solution throws an exception in case the method is called passing nil to error argument, try to call this:
 
```[FCFileManager createFileAtPath:@"test.txt" withContent:@"test" error:nil];```

**Comment by googoodalls** [comment]
Thank you for your prompt reply! :+1: 

I will update the code accordingly  : - )

**Comment by fabiocaccamo** [comment]
Don't worry, I already released an updated pod
