### ISSUE TITLE
Return wrong data of type JSON

### ISSUE THREAD

**Issue by DikeyKing** [fabiocaccamo/FCFileManager#22]
+(NSJSONSerialization *)readFileAtPathAsJSON:(NSString *)path error:(NSError **)error
{
    NSData *data = [self readFileAtPathAsData:path error:error];
    
    if([self isNotError:error])
    {
        NSJSONSerialization *json = [NSJSONSerialization JSONObjectWithData:data options:0 error:error];
        
        if([NSJSONSerialization isValidJSONObject:json])
        {
            return json;
        }
    }
    
    return nil;
}

It should be id/NSArray/NSDictionary...

**Comment by fabiocaccamo** [comment]
Since *.json value could be NSArray or NSDictionary, you should cast the returned value:

```objective-c
NSString *testPath = [FCFileManager pathForMainBundleDirectoryWithPath:@"test.json"];
NSDictionary *test = (NSDictionary *)[FCFileManager readFileAtPathAsJSON:testPath];
NSLog(@"%@", test);
```
