### ISSUE TITLE
Transform video file from library to NSData object, using full path to that video (in Swift)

### ISSUE THREAD

**Issue by zlatibor** [fabiocaccamo/FCFileManager#24]
How read video file from video library on the phone if we know full path to video file, for example:
`/private/var/mobile/Media/DCIM/100APPLE/IMG_0011.MOV
`

I tried to use that path in NSData like this:
`let videoData = try NSData(contentsOfFile: "/private/var/mobile/Media/DCIM/100APPLE/IMG_0011.MOV", options: NSDataReadingOptions.DataReadingMappedIfSafe)`

but I receive this error:

> Error Domain=NSCocoaErrorDomain Code=257
> 
> "The file “IMG_0011.MOV” couldn’t be opened because you don’t have permission to view it."
> 
> UserInfo={NSFilePath=/private/var/mobile/Media/DCIM/100APPLE/IMG_0011.MOV, NSUnderlyingError=0x17d88fc0 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}

Reading (loading) video file from folder (path) in the aplication works fine, but reading from path that is not in the application folder (like path above) does not work.

So, my question is: **how read (get) video file from phone's video library (using full video path) and transform to NSData object, but without saving any data to the disc (using RAM only) during that process?**

**Comment by fabiocaccamo** [comment]
Hi @zlatibor, 
you are not using FCFileManager, you could try to do the following: 

```objective-c
NSError *error;
NSData *data = [FCFileManager readFileAtPathAsData:youVideoPath error:&error];
```

In any case the problem seems to be related to permissions, check this: http://stackoverflow.com/questions/24924809/the-file-myapp-app-couldnt-be-opened-because-you-dont-have-permission-to-vi

**Comment by zlatibor** [comment]
Hi fabiocaccamo !

I tried all but none of them works.

Could you make it to works on your real Apple device, if you have time, please?

This problem makes to me a lot of problems.

**Comment by fabiocaccamo** [comment]
Hi @zlatibor,
I'm sorry but at the moment I have not time to do it.

I will close this issue since it is not related to the lib itself.
