### ISSUE TITLE
Sort File By Size, Name, Create date

### ISSUE THREAD

**Issue by veila** [fabiocaccamo/FCFileManager#25]
Does FCFileManager have sort functions when list items in directory?

<a href="https://dashboard.polar.sh/fabiocaccamo/FCFileManager/issues/25">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/FCFileManager/issues/25/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/FCFileManager/issues/25/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@veila Actually sorting is not supported, but it is an interesting new feature.
