### ISSUE TITLE
objectAtIndexedSubscript: requires iOS6.0

### ISSUE THREAD

**Issue by Oggerschummer** [fabiocaccamo/FCFileManager#28]
The minimum target needs to be raised from 5.0 to 6.0, otherwise there is always a compiler warning about objectAtIndexedSubscript: being only available in 6.0 or later.

`tokens[multiplyFactor]` in FileManager.m, sizeFormatted:

<a href="https://dashboard.polar.sh/fabiocaccamo/FCFileManager/issues/28">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/FCFileManager/issues/28/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/FCFileManager/issues/28/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
Feel free to submit a PR
