### ISSUE TITLE
Security Issue - Insecure Storage: Lacking Data Protection

### ISSUE THREAD

**Issue by harishios** [fabiocaccamo/FCFileManager#29]
We got lot of security issues in _FCFileManager.m_ saying - Insecure Storage: Lacking Data Protection

Example:
      `[[((NSString *)content) dataUsingEncoding:NSUTF8StringEncoding] writeToFile:absolutePath atomically:YES];`

<a href="https://dashboard.polar.sh/fabiocaccamo/FCFileManager/issues/29">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://dashboard.polar.sh/api/github/fabiocaccamo/FCFileManager/issues/29/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://dashboard.polar.sh/api/github/fabiocaccamo/FCFileManager/issues/29/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
@shukob feel free to submit a PR.
