### ISSUE TITLE
support url 

### ISSUE THREAD

**Issue by Nododo** [fabiocaccamo/FCFileManager#32]
hi

copy appshare file or UIDocumentPickerViewController file as url not support

i hope FCFileManager support this feature

thanks

wish you healthy and happy in work

**Comment by fabiocaccamo** [comment]
@Nododo could you try to explain better the feature you would like to have please?

**Comment by Nododo** [comment]
![05_2688_en](https://github.com/fabiocaccamo/FCFileManager/assets/10458305/7b753001-6cc7-4a5d-b091-4e345f31af10)

copy file from app share or copy file from the File app

i tried, it now not supports this 

i hope it will supports this

**Comment by fabiocaccamo** [comment]
Could you submit a PR?

**Comment by Nododo** [comment]
> Could you submit a PR?
sorry 

wish a superman can do this

**Comment by fabiocaccamo** [comment]
@Nododo I close this because it's not my intention to work on it, if you will work on a PR I will be glad to review and merge it.
