### ISSUE TITLE
#import <UIKit/UIKit.h> instead of <Foundation/Foundation.h>?

### ISSUE THREAD

**Issue by horaceho** [fabiocaccamo/FCFileManager#7]
There is an error: 
 
  `FCFileManager.h:96:3: Expected a type`

as UIImageView probably needs `<UIKit/UIKit.h>`. 

Fixed by replacing `#import <Foundation/Foundation.h>` with:

  `#import <UIKit/UIKit.h>`

**Comment by fabiocaccamo** [comment]
fixed and released 1.0.7 pod, thanks.
