### ISSUE TITLE
Path directories

### ISSUE THREAD

**Issue by Quisher** [fabiocaccamo/FCFileManager#8]
When asking for paths from fcfilemanager it does not put the final / at the end of path. Lets say i want a file from mainBunbdle. Then in order to get its path I will have to do this

FCFileManager.pathForMainBundleDirectory()+"/"+fileName

So I have to enter that "/". I was wondering that should be the default behaviour for the defaul paths.

**Comment by fabiocaccamo** [comment]
Why you don't use:
```objective-c
[FCFileManager pathForMainBundleDirectoryWithPath:fileName]
```

**Comment by Quisher** [comment]
oh guess in presence of that my concern is void.
