### ISSUE TITLE
Overwrite support

### ISSUE THREAD

**Issue by kartikthapar** [fabiocaccamo/FCFileManager#9]
I understand that this is a minor API change but have the ability to specify overwrite flag when creating files would be helpful.

Thanks! :)

**Comment by fabiocaccamo** [comment]
You're right, I'm going to add it.

**Comment by mikebryant71** [comment]
+1 for overwrite support, if you're just trying to copy or move files it would be really helpful to have this feature

**Comment by fabiocaccamo** [comment]
Added overwrite support and released 1.0.17 pod
